#!/bin/bash

#------------------------------------------------------------------------------
## VulaSHAKA (Simultaneous Neutronic, Fuel Performance, Heat And Kinetics Analysis)
## Copyright (C) 2009-2010 Pebble Bed Modular Reactor (Pty) Limited (PBMR)
## 
## This program is free software: you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation, either version 3 of the License, or
## (at your option) any later version.
##
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
## 
## You should have received a copy of the GNU General Public License
## along with this program.  If not, see <http://www.gnu.org/licenses/>.
## 
## See https://vulashaka.svn.sourceforge.net/svnroot/vulashaka/pyfoam/testing
##
## Author : Alexey PETROV
##


#------------------------------------------------------------------------------
# Get application name
application="parallel_diffusion"

if [ -f ${PARAFOAM_TESTING_DIR}/bin/${application} ] ; then
    echo Compile \"\${PARAFOAM_TESTING_DIR}/bin/${application}\" to perform this test
    exit 0
fi

cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
source ${PARAFOAM_TESTING_DIR}/Foam/RunFunctions


#------------------------------------------------------------------------------
cases="nuclear temperature"
for case in ${cases} ; do
    runApplication blockMesh ${case}
done

runBasic ${application} ${application} `pwd` .


#------------------------------------------------------------------------------
