/*-------------------------------------------------------------------------------------------------
    Copyright PBMR Pty Ltd.
    This file is a property of PBMR Pty Ltd, Centurion, Pretoria, South Africa. All rights reserved.
    No part of this source code may be reproduced, stored in a retrieval system or transmitted in
    any form or by any means, electronic, mechanical, photocopying, recording or otherwise without
    the prior written permission of the company.
    Name:
        extrapolatedLengthFvPatchFieldsFwd.H
    Class:
        extrapolatedLengthFvPatchField
    Description:
        Extrapolated length boundary field for scalar neutron flux, forward declaration

-------------------------------------------------------------------------------------------------*/

#ifndef extrapolatedLengthFvPatchFieldsFwd_H
#define extrapolatedLengthFvPatchFieldsFwd_H

#include "fieldTypes.H"

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

namespace Foam
{

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

template<class Type> class extrapolatedLengthFvPatchField;

makePatchTypeFieldTypedefs(extrapolatedLength)

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

} // End namespace Foam

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

#endif

// ************************************************************************* //
