/*-------------------------------------------------------------------------------------------------
    Copyright PBMR Pty Ltd.
    This file is a property of PBMR Pty Ltd, Centurion, Pretoria, South Africa. All rights reserved.
    No part of this source code may be reproduced, stored in a retrieval system or transmitted in
    any form or by any means, electronic, mechanical, photocopying, recording or otherwise without
    the prior written permission of the company.
    Name:
        extrapolatedLengthFvPatchFields.H
    Class:
        extrapolatedLengthFvPatchField
    Description:
        Extrapolated length boundary field for scalar neutron flux, namespace declaration
    SourceFiles:
        extrapolatedLengthFvPatchFields.C
-------------------------------------------------------------------------------------------------*/

#ifndef extrapolatedLengthFvPatchFields_H
#define extrapolatedLengthFvPatchFields_H

#include "extrapolatedLengthFvPatchField.H"
#include "fieldTypes.H"

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

namespace Foam
{

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

makePatchTypeFieldTypedefs(extrapolatedLength)

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

} // End namespace Foam

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

#endif

// ************************************************************************* //
