#!/bin/bash

#------------------------------------------------------------------------------
## VulaSHAKA (Simultaneous Neutronic, Fuel Performance, Heat And Kinetics Analysis)
## Copyright (C) 2009-2010 Pebble Bed Modular Reactor (Pty) Limited (PBMR)
## 
## This program is free software: you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation, either version 3 of the License, or
## (at your option) any later version.
##
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
## 
## You should have received a copy of the GNU General Public License
## along with this program.  If not, see <http://www.gnu.org/licenses/>.
## 
## See https://vulashaka.svn.sourceforge.net/svnroot/vulashaka/pyfoam/testing
##
## Author : Alexey PETROV
##


#------------------------------------------------------------------------------
# Source basic functionality
source ${WM_PROJECT_DIR}/tutorials/RunFunctions


#------------------------------------------------------------------------------
# Customize some functions
runBasic ()
{
    app_run=${1}; shift
    app_name=${1}; shift

    if [ -f ${2}/log.${app_name} ] ; then
        echo "( cd `pwd` && ${app_run} $* ) - already run; remove log file to run"
    else
        echo "( cd `pwd` && ${app_run} $* )"
        ${app_run} $* > ${2}/log.${app_name} 2>&1
	if [ $? -ne 0 ] ; then
	    echo "An error have appeared during execution of" ${app_name} :
	    cat ${2}/log.${app_name}
	    rm ${2}/log.${app_name}
	fi
    fi
}


#------------------------------------------------------------------------------
# Customize some functions
runApplication ()
{
   app_run=${1}; shift
   app_name=`basename ${app_run}`

   runBasic ${app_run} ${app_name} . $*
}


#------------------------------------------------------------------------------
