#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
set -x

wmakeLnInclude radiation

( cd radiation/Make && make )

# ----------------------------------------------------------------- end-of-file
